version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - /var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: appUser
      POSTGRES_PASSWORD: 13
      POSTGRES_DB: ined_db
      PGDATA: /var/lib/postgresql/data/pgdata

 
